#!/bin/sh
SELF_DIR="$(dirname "$(readlink -f "$0")")"
LIBS_PATH="$SELF_DIR/lib:$SELF_DIR/lib/x86_64-linux-gnu:$SELF_DIR/usr/lib:$SELF_DIR/usr/lib/x86_64-linux-gnu"

if [ -z "$LD_LIBRARY_PATH" ]; then
  LD_LIBRARY_PATH="$LIBS_PATH"
else
  LD_LIBRARY_PATH="$LIBS_PATH:$LD_LIBRARY_PATH"
fi

export LD_LIBRARY_PATH

if [ ! -f $HOME/.Heroes\ of\ Newerth/.bin/game/resources0.s2z ]
then
	mkdir -p $HOME/.Heroes\ of\ Newerth/.bin
	rsync -rcEl $SELF_DIR/opt/HoN/ $HOME/.Heroes\ of\ Newerth/.bin
	
	if [ ! -f $HOME/.Heroes\ of\ Newerth/.bin/vid_gl2-x86_64.so ]
	then $SELF_DIR/usr/bin/wget -O $HOME/.Heroes\ of\ Newerth/.bin/vid_gl2.zip http://dl.heroesofnewerth.com/lac/x86-biarch/4.5.3/vid_gl2-x86_64.so.zip
		$SELF_DIR/usr/bin/unzip $HOME/.Heroes\ of\ Newerth/.bin/vid_gl2.zip -d $HOME/.Heroes\ of\ Newerth/.bin
		rm $HOME/.Heroes\ of\ Newerth/.bin/vid_gl2.zip
	fi
	
	if [ ! -f $HOME/.Heroes\ of\ Newerth/.bin/libs-x86_64/libawesomium-1-7.so.5 ]
	then $SELF_DIR/usr/bin/wget -O $HOME/.Heroes\ of\ Newerth/.bin/libs-x86_64/libawesomium-1-7.so.5.zip http://dl.heroesofnewerth.com/lac/x86-biarch/3.7.10/libs-x86_64/libawesomium-1-7.so.5.zip
		$SELF_DIR/usr/bin/unzip $HOME/.Heroes\ of\ Newerth/.bin/libs-x86_64/libawesomium-1-7.so.5.zip -d $HOME/.Heroes\ of\ Newerth/.bin/libs-x86_64
		rm $HOME/.Heroes\ of\ Newerth/.bin/libs-x86_64/libawesomium-1-7.so.5.zip
	fi
	
	exec $HOME/.Heroes\ of\ Newerth/.bin/hon-x86_64 -repair
fi

for udevpath in /lib/x86_64-linux-gnu/libudev.so.1 /usr/lib64/libudev.so.1 /usr/lib/libudev.so.1 /lib/i386-linux-gnu/libudev.so.1 /lib64/libudev.so.1 /lib/libudev.so.1 ; do
  if [ -f "$udevpath" ]; then
    # Map libudev.so.1 to libudev.so.0, if necessary
    ln -sf "$udevpath" $HOME/.Heroes\ of\ Newerth/.bin/libs-x86_64/libudev.so.0
    break
  fi
done

export LD_PRELOAD="$SELF_DIR/usr/lib64/libfreetype.so"
exec $HOME/.Heroes\ of\ Newerth/.bin/hon-x86_64 "$*"
