#!/bin/sh
SELF_DIR="$(dirname "$(readlink -f "$0")")"
LIBS_PATH="$SELF_DIR/usr/lib64"

if [ -z "$LD_LIBRARY_PATH" ]; then
  LD_LIBRARY_PATH="$LIBS_PATH"
else
  LD_LIBRARY_PATH="$LIBS_PATH:$LD_LIBRARY_PATH"
fi

export LD_LIBRARY_PATH

if [ ! -f "$HOME/.Heroes of Newerth/.bin/game/resources0.s2z" ]
then
  DOWNLOAD_DIR="$HOME/.Heroes of Newerth/.bin"
  mkdir -p "$DOWNLOAD_DIR/hon-downloader"
  cd "$DOWNLOAD_DIR/hon-downloader"
  $SELF_DIR/usr/bin/wget -q -O manifest.xml.zip http://dl.heroesofnewerth.com/lac/x86-biarch/{{ hon_version }}/manifest.xml.zip
  $SELF_DIR/usr/bin/unzip -q -o manifest.xml.zip

  for path in "" game/ libs-x86_64/ base/ updater_resources/
  do
    mkdir -p "${DOWNLOAD_DIR}/${path}"
    cd "${DOWNLOAD_DIR}/${path}"
    for url in `grep -i "<file path=\"$path[^/]*\"" "$DOWNLOAD_DIR/manifest.xml" | sed 's~.*path="\([^"]*\)".*version="\([^"]*\)\.[0-9]".*~http://dl.heroesofnewerth.com/lac/x86-biarch/\2/\1.zip~'`
    do
      $SELF_DIR/usr/bin/wget -q -O output.zip $url
      $SELF_DIR/usr/bin/unzip -q -o output.zip
      rm output.zip
    done
    pwd
    ls
    cd "$SELF_DIR"
  done

  chmod +x "$HOME/.Heroes of Newerth/.bin/hon-x86_64"
	
  exec "$HOME/.Heroes of Newerth/.bin/hon-x86_64" "-repair"
fi

for udevpath in /lib/x86_64-linux-gnu/libudev.so.1 /usr/lib64/libudev.so.1 /usr/lib/libudev.so.1 /lib/i386-linux-gnu/libudev.so.1 /lib64/libudev.so.1 /lib/libudev.so.1 ; do
  if [ -f "$udevpath" ]; then
    # Map libudev.so.1 to libudev.so.0, if necessary
    ln -sf "$udevpath" "$HOME/.Heroes of Newerth/.bin/libs-x86_64/libudev.so.0"
    break
  fi
done

exec "$HOME/.Heroes of Newerth/.bin/hon-x86_64" "$*"
