- name: Create docker-image
  docker_image:
    name: hon-appimage
    build:
      path: ../
      dockerfile: BaseImage/Gentoo.dockerfile
      pull: no
    force_source: no
    source: build

- name: Create docker-container
  docker_container:
    name: hon-ansible
    image: hon-appimage
    recreate: yes
    devices:
      - /dev/fuse
      - /dev/snd
    volumes:
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
      - binpkgs:/var/cache/binpkgs
    env:
      DISPLAY: ":0"
    capabilities:
      - sys_admin
    state: started
    entrypoint: /bin/sleep
    command: "3600"
    tty: yes
    detach: yes
    init: yes

- name: Register container as ansible-host
  add_host:
    name: "hon-ansible"
    ansible_connection: docker
    ansible_python_interpreter: python3
  changed_when: false
