- name: Fetch script
  copy:
    src: tempenv.sh
    dest: /mnt/tempenv.sh
    mode: "550"

- name: Fetch AppImageKit
  get_url:
    url: https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
    dest: /opt/appimagetool-x86_64.AppImage
    mode: "550"
    validate_certs: no

- name: Create Link for unionfs mount
  file:
    dest: /usr/bin/unionfs-fuse
    src: /usr/bin/unionfs
    state: link

- name: Check for setup
  stat: path=/mnt/tempenv/dev
  register: dev

- name: Check for AppDir
  stat: path=/mnt/HoN.AppDir
  register: appDir

- name: Setup Temp-Env
  when: not (dev.stat.isdir is defined and dev.stat.isdir)
  shell:
    cmd: ./tempenv.sh setup
    chdir: /mnt/

- name: Start Temp-Env
  shell:
    cmd: >      
      ./tempenv.sh start <<EOF
      
      apt-get install --no-install-recommends -y 
      libxml2 libgdk-pixbuf2.0-0 
      libcairo2 libcups2 libnss3 libasound2 
      libpangocairo-1.0-0 
      libkeyutils1
      
      apt-get --reinstall install --no-install-recommends -y
      libffi6
      libharfbuzz0b
      libfontconfig1
      libfreetype6
      
      exit $?
      
      EOF
    chdir: /mnt
  when: ansible_facts['os_family'] == "Debian"

- name: Start Temp-Env
  shell:
    cmd: >
      MAKEOPTS="-j3"
      USE="-introspection"
      emerge -vbkn --jobs=2
      @hon-tempenv
      &&
      
      ./tempenv.sh start <<EOF
      
      MAKEOPTS="-j3"
      USE="-introspection"
      emerge -vk --jobs=2
      @hon-tempenv
      
      exit $?
      
      EOF
    chdir: /mnt
  when: ansible_facts['os_family'] == "Gentoo42"

- name: Copy files to AppDir
  shell:
    cmd: cp -r tempenv/files HoN.AppDir
    chdir: /mnt

- name: Prepare AppDir
  file:
    path: /mnt/HoN.AppDir/opt
    state: directory

- name: Copy Desktop-File to AppDir
  copy:
    src: s2games_com-HoN_1.desktop
    dest: /mnt/HoN.AppDir/s2games_com-HoN_1.desktop
    mode: "550"

- name: Copy Icon-File
  copy:
    src: honicon_128x128.png
    dest: /mnt/HoN.AppDir/honicon_128x128.png

#- name: Copy MetaInfo
#  copy:
#    src: metainfo
#    dest: /usr/share/metainfo

- name: Copy AppRun
  template:
    src: AppRun
    dest: /mnt/HoN.AppDir/AppRun
    mode: "550"
  vars:
    hon_version: "4.8.4"

- name: Delete non-library files
  file:
    state: absent
    path: "/mnt/HoN.AppDir/{{ item }}"
  loop:
    - usr/share/
    - usr/include
    - usr/libexec
    - var

- name: Build AppImage
  shell:
    cmd: ARCH=x86_64 /opt/appimagetool-x86_64.AppImage HoN.AppDir
    chdir: /mnt

- name: Extract AppImage
  fetch:
    src: /mnt/Heroes_Of_Newerth-x86_64.AppImage
    dest: ../Heroes_Of_Newerth-x86_64.AppImage
    flat: yes
